#!/usr/bin/env bash
# =============================================================================
# install_service.sh — Register IDIA Server as a systemd service
# =============================================================================
#
# Generates a systemd unit file that ensures the server starts on boot.
# Must be run as root (called via ``sudo ./idia service install``).
#
# The unit uses Type=oneshot with RemainAfterExit=yes so systemd considers
# the service active even after ``docker compose up -d`` exits. Docker's
# ``restart: unless-stopped`` then handles individual container recovery.
# =============================================================================

set -euo pipefail

# ── Paths ────────────────────────────────────────────────────────────────────

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
UNIT_NAME="idia-server"
UNIT_FILE="/etc/systemd/system/${UNIT_NAME}.service"

# ── Colours ──────────────────────────────────────────────────────────────────

if [ -t 1 ] && command -v tput &>/dev/null; then
    GREEN="$(tput setaf 2)"
    YELLOW="$(tput setaf 3)"
    RESET="$(tput sgr0)"
else
    GREEN="" YELLOW="" RESET=""
fi

_info()  { echo "${GREEN}[✓]${RESET} $*"; }
_warn()  { echo "${YELLOW}[⚠]${RESET} $*"; }

# ── Pre-flight checks ────────────────────────────────────────────────────────

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root. Use:  sudo ./idia service install" >&2
    exit 1
fi

if [ ! -f "$REPO_DIR/docker-compose.yml" ]; then
    echo "docker-compose.yml not found at $REPO_DIR — wrong directory?" >&2
    exit 1
fi

# ── Generate unit file ───────────────────────────────────────────────────────

cat > "$UNIT_FILE" << UNITEOF
# IDIA Server — systemd unit (generated by install_service.sh)
# Do NOT edit manually. Run \`sudo ./idia service uninstall\` to remove.

[Unit]
Description=IDIA Server — LLM Inference Stack
Documentation=https://github.com/PUC-Behring-Institute-for-AI/idia-server
Wants=docker.service
After=docker.service network-online.target
RequiresMountsFor=/var/lib/docker

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${REPO_DIR}
ExecStart=/bin/bash ${REPO_DIR}/idia deploy local --no-wait
ExecStop=/bin/bash ${REPO_DIR}/idia stop
Restart=on-failure
RestartSec=30
TimeoutStartSec=900
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNITEOF

_info "Unit file written: $UNIT_FILE"

# ── Register with systemd ────────────────────────────────────────────────────

systemctl daemon-reload
_info "systemd daemon reloaded"

systemctl enable "$UNIT_NAME"
_info "Service enabled — starts automatically on boot"

# ── Start the service now ────────────────────────────────────────────────────

echo ""
echo "Starting service now..."
if systemctl start "$UNIT_NAME"; then
    _info "Service started"
else
    _warn "Service start failed — check logs with:  journalctl -u $UNIT_NAME -f"
    exit 1
fi

echo ""
echo "${GREEN}══════════════════════════════════════${RESET}"
echo "${GREEN}  IDIA Server service installed${RESET}"
echo "${GREEN}══════════════════════════════════════${RESET}"
echo ""
echo "  Status:      ./idia service status"
echo "  Logs:        journalctl -u $UNIT_NAME -f"
echo "  Stop:        sudo systemctl stop $UNIT_NAME"
echo "  Uninstall:   sudo ./idia service uninstall"
echo ""
